### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [aws/amazon-s3-encryption-client-dotnet#11]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/csharp/
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by ganeshnj** [comment]
[1.2.1](https://www.nuget.org/packages/Amazon.Extensions.S3.Encryption/) is out with fix.

Resolving.

**Comment by Neustradamus** [comment]
@ganeshnj: Thanks a lot! :)

**Comment by Neustradamus** [comment]
@ganeshnj: Can you update to 1.8.10?
