### ISSUE TITLE
The content encryption algorithm used at encryption time does not match the algorithm stored for decryption time. The object may be altered or corrupted.

### ISSUE THREAD

**Issue by wnmendonca** [aws/amazon-s3-encryption-client-dotnet#26]
## Description
I am using SES rule set to save encrypted messages in a S3 bucket. The messages are encrypted using kms key.
When I try to get this objects using Amazon S3 Encryption client for .NET, I have a error:
The content encryption algorithm used at encryption time does not match the algorithm stored for decryption time. The object may be altered or corrupted.
I noticed that sdk is validate a material description metadata and in this json doesn't have encryption context property (aws:x-amz-cek-alg).

![image](https://user-images.githubusercontent.com/11818537/132374474-ef97af9a-6359-401b-8b82-5ae9a7c6972b.png)

![image](https://user-images.githubusercontent.com/11818537/132372855-6a42a22a-cd43-4de1-8478-f3cfdbd2b8f2.png)

Not is possible to set this property in request encryption context, I have a error: 
Conflict in reserved KMS Encryption Context key aws:x-amz-cek-alg. This value is reserved for the S3 Encryption Client and cannot be set by the use

## Reproduction Steps
Try to get a encrypted object saved in S3 by a SES rule set.

### Environment

* SDK Version: 2.0.3
* Package Version: 2.0.3
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  .Net Core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by imre-turi-cko** [comment]
We are having the same issue, could you give an update please?

**Comment by justinrhammonds** [comment]
I am having the same issue. Any updates on this would be really appreciated! 

To anyone else encountering this issue... have you determined a suitable workaround or alternative? Would love to hear how your handling this. My org has the requirement (not so much an option) that we encrypt the emails SES receives, so decryption is necessary one way or another.

**Comment by wnmendonca** [comment]
Hi Justin, I stopped using encryption using SES and used only encryption on the S3 bucket.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html
But you can try using another framework like Node.js.
https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/s3-example-client-side-decrypt-item-with-kms-master-key.html

**Comment by CamileDahdah** [comment]
Hi there, 
Thank you creating this issue. 
Can you post the same code that you wrote which is failing? That way I can make sure that I am addressing the problem you are facing. Also, are you using AmazonS3EncryptionClientV2 or AmazonS3EncryptionClient?

Thank you.

**Comment by CamileDahdah** [comment]
Thanks you @wnmendonca, and everyone who was involved in this thread. 
We have finally released a fix for this bug as part of this [PR](https://github.com/aws/amazon-s3-encryption-client-dotnet/pull/40). The fix has also been released in version 2.0.5 of NuGet package Amazon.Extensions.S3.Encryption on 02/13/2023.

**Comment by CamileDahdah** [comment]
Please note that you should set your AmazonS3EncryptionClient configuration to"SecurityProfile.V2AndLegacy" for it to work.
