### ISSUE TITLE
Timeout set on the S3Client does not apply to the internal KMS client

### ISSUE THREAD

**Issue by 1rjt** [aws/amazon-s3-encryption-client-dotnet#31]
## Description
A client timeout can be set via AmazonS3CryptoConfigurationV2.Timeout but this value is not used by the internal KMSClient. The internal KMS client does not have a timeout set so is always 100 seconds

The only value copied over to the KMS client config is region endpoint https://github.com/aws/amazon-s3-encryption-client-dotnet/blob/main/src/AmazonS3EncryptionClientBase.cs#L54

## Reproduction Steps

1. Create AmazonS3EncryptionClientV2 with timeout set to 5 seconds
2. Use client in network with slow/varied performance. 
3. Calls can exceed 5 seconds due to the internal KMS client call.

### Environment

* SDK Version:  2.0.3
* Package Version:  Amazon.Extensions.S3.Encryption version 2.0.3
* OS Info:  Windows 10 & Mac & AmazonLinux 
* Build Environment  Visual Studio
* Targeted .NET Platform:  .net 5.0

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashovlin** [comment]
Hello, there are now two possible ways to work around this:

1. In [version 2.0.4](https://www.nuget.org/packages/Amazon.Extensions.S3.Encryption/2.0.4) and later, we began copying the timeout specified on the S3 configuration to the configuration for the internal KMS client.

```
var config = new AmazonS3CryptoConfigurationV2(securityProfile)
{
    Timeout = TimeSpan.FromSeconds(10) // this will apply to both S3 and KMS
}
```

2. In [version 2.1.0](https://www.nuget.org/packages/Amazon.Extensions.S3.Encryption/2.1.0) that was released today, you can now optionally configure the internal KMS client independently of the S3 client.

```
 var config = new AmazonS3CryptoConfigurationV2(securityProfile)
 {
     KmsConfig = new AmazonKeyManagementServiceConfig
     {
         Timeout = TimeSpan.FromSeconds(10) // this will only apply to KMS
     }
 };
```
