### ISSUE TITLE
Update BouncyCastle dependency

### ISSUE THREAD

**Issue by simenstensas** [aws/amazon-s3-encryption-client-dotnet#55]
### Describe the bug

Please remove [BouncyCastle](https://www.nuget.org/packages/BouncyCastle) dependency and replace it with [BouncyCastle.Cryptography v2.4.0](https://www.nuget.org/packages/BouncyCastle.Cryptography/)

See: https://github.com/advisories/GHSA-8xfc-gm6g-vgpv

### Expected Behavior

Works as intended

### Current Behavior

Outdated dependency

### Reproduction Steps

Nothing to write

### Possible Solution

Changing dependency to BouncyCastle.Cryptography and solving possible breaking changes.

### AWS .NET SDK and/or Package version used

AWSSDK.* 3.7.400.5

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 11

**Comment by bhoradc** [comment]
Hello @simenstensas,

Thank you for reporting this issue. In [S3 Encryption Client for .NET](https://github.com/aws/amazon-s3-encryption-client-dotnet) library, the `BouncyCastle` dependency is used when `TargetFramework` is .NET 3.5 alone, for others it's using the `Portable.BouncyCastle` package - [Reference link](https://github.com/aws/amazon-s3-encryption-client-dotnet/blob/ad92c45a34bf70b3b52e7362df83bbff6601def8/src/Amazon.Extensions.S3.Encryption.csproj#L49).

We shall get rid of the `BouncyCastle` package, when we update this library for the V4 effort, where .NET Framework 3.5 target would been removed.

Regards, 
Chaitanya

**Comment by simenstensas** [comment]
Hi @bhoradc, 

I understand. When can we expect a V4 release? Any timeline?

**Comment by normj** [comment]
@simenstensas I can't give an expected release for V4 because we always have lots of competing tasks supporting all AWS services. The first preview of V4 went out last week and the intention is for V4 to have a relatively short dev cycle to get to GA state.

**Comment by simenstensas** [comment]
@bhoradc Will `Portable.BouncyCastle` dependency be removed as a part of V4 as well?

**Comment by normj** [comment]
@simenstensas Yes all targets will use [BouncyCastle.Cryptography](https://github.com/aws/amazon-s3-encryption-client-dotnet/blob/v4sdk-development/src/Amazon.Extensions.S3.Encryption.csproj#L38C36-L38C58) in v4. We have shipped `3.0.0-preview.1` of the package that targets V4 of the SDK and uses `BouncyCastle.Cryptography`.

**Comment by normj** [comment]
I'm closing the issue because we have made the switch to `BouncyCastle.Cryptography` for V4 and have released a preview version. You can track the progress of V4 going GA by subscribing to the following V4 tracking issue.

https://github.com/aws/aws-sdk-net/issues/3362
