### ISSUE TITLE
When using KMS, default profile is used instead of intended profile

### ISSUE THREAD

**Issue by freiguy1** [aws/amazon-s3-encryption-client-dotnet#6]
My local dev machine is set up with multiple AWS credential profiles. My ~/.aws/credentials contains

```text
[default]
aws_access_key_id = xxxxxxxxx
aws_secret_access_key = xxxxxxxxxx

[other-profile]
aws_access_key_id = xxxxxxxxx
aws_secret_access_key = xxxxxxxxxx
```

I want to use `other-profile` and that is working correctly with S3 _without_ client-side encryption. But when I use KMS client-side encryption and attempt `PutObject`, I get this exception:

>'User: [default] is not authorized to perform: kms:GenerateDataKey on resource: [my KMS id]'

When I expect to use `other-profile` profile instead of `default` profile.

Furthermore, when I inspect my `s3Client` while debugging, I see the correct credentials. But KMS isn't respecting them.
![image](https://user-images.githubusercontent.com/613651/95509747-7fd11100-097a-11eb-9b49-acf2f638b4af.png)

**Comment by normj** [comment]
Thanks for reporting the issue. We have identified what is going wrong in the code and working on getting a fix out.

**Comment by normj** [comment]
Version 1.2.0 has been released with the fix.

**Comment by freiguy1** [comment]
It verks!

Thanks for the super fast turnaround time.
